"""Added validation to the filters

Revision ID: 185eaf933e09
Revises: ebcec2e166a3
Create Date: 2025-06-14 13:06:57.989918

"""
from alembic import op
import sqlalchemy as saAdd


# revision identifiers, used by Alembic.
revision = '185eaf933e09'
down_revision = 'ebcec2e166a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###