"""Create ListingMobileDe, TechnicalDetails, Equipment tables

Revision ID: 1907eb1b2a13
Revises: 984c2ef9f137
Create Date: 2025-06-06 16:24:56.713695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1907eb1b2a13'
down_revision = '984c2ef9f137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_mobilede',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('registration_year', sa.Integer(), nullable=False),
    sa.Column('city_or_postal_code', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_listing_mobilede_brand'), 'listing_mobilede', ['brand'], unique=False)
    op.create_index(op.f('ix_listing_mobilede_city_or_postal_code'), 'listing_mobilede', ['city_or_postal_code'], unique=False)
    op.create_index(op.f('ix_listing_mobilede_color'), 'listing_mobilede', ['color'], unique=False)
    op.create_index(op.f('ix_listing_mobilede_id'), 'listing_mobilede', ['id'], unique=False)
    op.create_index(op.f('ix_listing_mobilede_is_active'), 'listing_mobilede', ['is_active'], unique=False)
    op.create_index(op.f('ix_listing_mobilede_mileage'), 'listing_mobilede', ['mileage'], unique=False)
    op.create_index(op.f('ix_listing_mobilede_model'), 'listing_mobilede', ['model'], unique=False)
    op.create_index(op.f('ix_listing_mobilede_price'), 'listing_mobilede', ['price'], unique=False)
    op.create_index(op.f('ix_listing_mobilede_registration_year'), 'listing_mobilede', ['registration_year'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('abs', sa.Boolean(), nullable=True),
    sa.Column('adaptive_cruise_control', sa.Boolean(), nullable=True),
    sa.Column('distance_warning', sa.Boolean(), nullable=True),
    sa.Column('all_wheel_drive', sa.Boolean(), nullable=True),
    sa.Column('ambient_lighting', sa.Boolean(), nullable=True),
    sa.Column('android_auto', sa.Boolean(), nullable=True),
    sa.Column('tow_bar_swiveling', sa.Boolean(), nullable=True),
    sa.Column('apple_carplay', sa.Boolean(), nullable=True),
    sa.Column('armrest', sa.Boolean(), nullable=True),
    sa.Column('heated_windshield', sa.Boolean(), nullable=True),
    sa.Column('bluetooth', sa.Boolean(), nullable=True),
    sa.Column('board_computer', sa.Boolean(), nullable=True),
    sa.Column('power_windows', sa.Boolean(), nullable=True),
    sa.Column('power_tailgate', sa.Boolean(), nullable=True),
    sa.Column('power_mirrors', sa.Boolean(), nullable=True),
    sa.Column('immobilizer', sa.Boolean(), nullable=True),
    sa.Column('esp', sa.Boolean(), nullable=True),
    sa.Column('high_beam_assist', sa.Boolean(), nullable=True),
    sa.Column('hands_free', sa.Boolean(), nullable=True),
    sa.Column('warranty', sa.Boolean(), nullable=True),
    sa.Column('speed_limiter', sa.Boolean(), nullable=True),
    sa.Column('wireless_charging', sa.Boolean(), nullable=True),
    sa.Column('auto_dimming_mirror', sa.Boolean(), nullable=True),
    sa.Column('isofix', sa.Boolean(), nullable=True),
    sa.Column('isofix_passenger', sa.Boolean(), nullable=True),
    sa.Column('leather_steering_wheel', sa.Boolean(), nullable=True),
    sa.Column('led_headlights', sa.Boolean(), nullable=True),
    sa.Column('led_daytime_running_lights', sa.Boolean(), nullable=True),
    sa.Column('alloy_wheels', sa.Boolean(), nullable=True),
    sa.Column('light_sensor', sa.Boolean(), nullable=True),
    sa.Column('lumbar_support', sa.Boolean(), nullable=True),
    sa.Column('drowsiness_warning', sa.Boolean(), nullable=True),
    sa.Column('multi_function_steering_wheel', sa.Boolean(), nullable=True),
    sa.Column('music_streaming', sa.Boolean(), nullable=True),
    sa.Column('navigation_system', sa.Boolean(), nullable=True),
    sa.Column('non_smoking_vehicle', sa.Boolean(), nullable=True),
    sa.Column('emergency_brake_assist', sa.Boolean(), nullable=True),
    sa.Column('emergency_call_system', sa.Boolean(), nullable=True),
    sa.Column('dab_radio', sa.Boolean(), nullable=True),
    sa.Column('rain_sensor', sa.Boolean(), nullable=True),
    sa.Column('tire_pressure_monitoring', sa.Boolean(), nullable=True),
    sa.Column('seat_heating', sa.Boolean(), nullable=True),
    sa.Column('sound_system', sa.Boolean(), nullable=True),
    sa.Column('sport_package', sa.Boolean(), nullable=True),
    sa.Column('sports_seats', sa.Boolean(), nullable=True),
    sa.Column('voice_control', sa.Boolean(), nullable=True),
    sa.Column('lane_keep_assist', sa.Boolean(), nullable=True),
    sa.Column('touchscreen', sa.Boolean(), nullable=True),
    sa.Column('traction_control', sa.Boolean(), nullable=True),
    sa.Column('radio', sa.Boolean(), nullable=True),
    sa.Column('usb', sa.Boolean(), nullable=True),
    sa.Column('traffic_sign_recognition', sa.Boolean(), nullable=True),
    sa.Column('digital_dashboard', sa.Boolean(), nullable=True),
    sa.Column('wifi_hotspot', sa.Boolean(), nullable=True),
    sa.Column('central_locking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing_mobilede.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_table('technical_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('damage_condition', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('trim_line', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('country_version', sa.String(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('engine_type', sa.String(), nullable=True),
    sa.Column('other_energy_source', sa.String(), nullable=True),
    sa.Column('battery', sa.String(), nullable=True),
    sa.Column('battery_capacity', sa.Float(), nullable=True),
    sa.Column('battery_certificate', sa.String(), nullable=True),
    sa.Column('battery_range', sa.Integer(), nullable=True),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('door_count', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('emissions_sticker', sa.String(), nullable=True),
    sa.Column('first_year_registration', sa.Integer(), nullable=True),
    sa.Column('first_month_registration', sa.Integer(), nullable=True),
    sa.Column('number_of_previous_owners', sa.String(), nullable=True),
    sa.Column('hu_year', sa.Integer(), nullable=True),
    sa.Column('hu_month', sa.Integer(), nullable=True),
    sa.Column('climatisation', sa.String(), nullable=True),
    sa.Column('park_assists', sa.String(), nullable=True),
    sa.Column('airbags', sa.String(), nullable=True),
    sa.Column('manufacturer_color_name', sa.String(), nullable=True),
    sa.Column('interior', sa.String(), nullable=True),
    sa.Column('trailer_load_braked', sa.Integer(), nullable=True),
    sa.Column('trailer_load_unbraked', sa.Integer(), nullable=True),
    sa.Column('net_weight', sa.Integer(), nullable=True),
    sa.Column('waranty_registration', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing_mobilede.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_technical_details_category'), 'technical_details', ['category'], unique=False)
    op.create_index(op.f('ix_technical_details_damage_condition'), 'technical_details', ['damage_condition'], unique=False)
    op.create_index(op.f('ix_technical_details_engine_type'), 'technical_details', ['engine_type'], unique=False)
    op.create_index(op.f('ix_technical_details_first_month_registration'), 'technical_details', ['first_month_registration'], unique=False)
    op.create_index(op.f('ix_technical_details_first_year_registration'), 'technical_details', ['first_year_registration'], unique=False)
    op.create_index(op.f('ix_technical_details_id'), 'technical_details', ['id'], unique=False)
    op.create_index(op.f('ix_technical_details_transmission'), 'technical_details', ['transmission'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_details_transmission'), table_name='technical_details')
    op.drop_index(op.f('ix_technical_details_id'), table_name='technical_details')
    op.drop_index(op.f('ix_technical_details_first_year_registration'), table_name='technical_details')
    op.drop_index(op.f('ix_technical_details_first_month_registration'), table_name='technical_details')
    op.drop_index(op.f('ix_technical_details_engine_type'), table_name='technical_details')
    op.drop_index(op.f('ix_technical_details_damage_condition'), table_name='technical_details')
    op.drop_index(op.f('ix_technical_details_category'), table_name='technical_details')
    op.drop_table('technical_details')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_listing_mobilede_registration_year'), table_name='listing_mobilede')
    op.drop_index(op.f('ix_listing_mobilede_price'), table_name='listing_mobilede')
    op.drop_index(op.f('ix_listing_mobilede_model'), table_name='listing_mobilede')
    op.drop_index(op.f('ix_listing_mobilede_mileage'), table_name='listing_mobilede')
    op.drop_index(op.f('ix_listing_mobilede_is_active'), table_name='listing_mobilede')
    op.drop_index(op.f('ix_listing_mobilede_id'), table_name='listing_mobilede')
    op.drop_index(op.f('ix_listing_mobilede_color'), table_name='listing_mobilede')
    op.drop_index(op.f('ix_listing_mobilede_city_or_postal_code'), table_name='listing_mobilede')
    op.drop_index(op.f('ix_listing_mobilede_brand'), table_name='listing_mobilede')
    op.drop_table('listing_mobilede')
    # ### end Alembic commands ###
