"""Create CarGurus table

Revision ID: 619332d7dc6b
Revises: 8185aa18b9ce
Create Date: 2025-07-04 09:54:54.573558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619332d7dc6b'
down_revision = '8185aa18b9ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargurus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('cargurus_brand', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargurus_cargurus_brand'), 'cargurus', ['cargurus_brand'], unique=False)
    op.create_index(op.f('ix_cargurus_entity_id'), 'cargurus', ['entity_id'], unique=True)
    op.create_index(op.f('ix_cargurus_id'), 'cargurus', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cargurus_id'), table_name='cargurus')
    op.drop_index(op.f('ix_cargurus_entity_id'), table_name='cargurus')
    op.drop_index(op.f('ix_cargurus_cargurus_brand'), table_name='cargurus')
    op.drop_table('cargurus')
    # ### end Alembic commands ###
