"""Rename cargurus_brand to label

Revision ID: 83877f79c803
Revises: 619332d7dc6b
Create Date: 2025-07-05 09:56:13.201926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83877f79c803'
down_revision = '619332d7dc6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargurus', sa.Column('label', sa.String(), nullable=True))
    op.drop_index('ix_cargurus_cargurus_brand', table_name='cargurus')
    op.create_index(op.f('ix_cargurus_label'), 'cargurus', ['label'], unique=False)
    op.drop_column('cargurus', 'cargurus_brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargurus', sa.Column('cargurus_brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cargurus_label'), table_name='cargurus')
    op.create_index('ix_cargurus_cargurus_brand', 'cargurus', ['cargurus_brand'], unique=False)
    op.drop_column('cargurus', 'label')
    # ### end Alembic commands ###
