"""Create gpt_prompt_log table

Revision ID: 913fc8c94373
Revises: 9b2306a36592
Create Date: 2025-05-21 14:18:41.288260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913fc8c94373'
down_revision = '9b2306a36592'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
