"""Added device_id field in license model

Revision ID: 984c2ef9f137
Revises: fd7bcbddcc78
Create Date: 2025-05-22 12:57:34.670212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984c2ef9f137'
down_revision = 'fd7bcbddcc78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license_keys', sa.Column('device_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license_keys', 'device_id')
    # ### end Alembic commands ###
