"""Added filter field to the LicenseKey model

Revision ID: adf248c1d05e
Revises: 1907eb1b2a13
Create Date: 2025-06-14 08:26:06.150219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adf248c1d05e'
down_revision = '1907eb1b2a13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license_keys', sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license_keys', 'filters')
    # ### end Alembic commands ###