"""Fixed warranty field

Revision ID: be9179ac1643
Revises: 185eaf933e09
Create Date: 2025-06-16 12:48:38.380560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9179ac1643'
down_revision = '185eaf933e09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technical_details', sa.Column('warranty_registration', sa.String(), nullable=True))
    op.drop_column('technical_details', 'waranty_registration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technical_details', sa.Column('waranty_registration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('technical_details', 'warranty_registration')
    # ### end Alembic commands ###
