"""Added validation to the filters

Revision ID: ebcec2e166a3
Revises: adf248c1d05e
Create Date: 2025-06-14 12:55:33.211365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcec2e166a3'
down_revision = 'adf248c1d05e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###