"""Create gpt_prompt_log table

Revision ID: fd7bcbddcc78
Revises: 913fc8c94373
Create Date: 2025-05-21 14:36:09.520651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7bcbddcc78'
down_revision = '913fc8c94373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpt_prompt_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('gpt_prompt', sa.Text(), nullable=True),
    sa.Column('gpt_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpt_prompt_logs_id'), 'gpt_prompt_logs', ['id'], unique=False)
    op.create_index(op.f('ix_gpt_prompt_logs_user_id'), 'gpt_prompt_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpt_prompt_logs_user_id'), table_name='gpt_prompt_logs')
    op.drop_index(op.f('ix_gpt_prompt_logs_id'), table_name='gpt_prompt_logs')
    op.drop_table('gpt_prompt_logs')
    # ### end Alembic commands ###
